#! /bin/sh

sxhkd &
picom -f & 
nm-applet &
mpd &

feh --bg-scale ~/Pictures/Wallpaper/wallace.png &
# Launch polybar
$HOME/.config/polybar/launch.sh &

bspc monitor eDP1 -d 1 2 4 7 9
bspc monitor HDMI1 -d 3 5 6 8 


bspc config border_width         1
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true



bspc config active_border_color "#2f343f"
bspc config focused_border_color "#1ee3ae"
bspc config presel_feedback_color "#2f343f"
bspc config normal_border_color "#2f343f"
bspc config urgent_border_color "#f54e4e" 

bspc rule -a discord desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^3'
bspc rule -a vlc desktop='^4' follow=on
bspc rule -a spotify desktop='^9' state=floating follow=on

# Wallpaper

