#! /bin/sh

sxhkd &
picom -f & 
nm-applet &
xfce4-power-manager&
mpd &
#xinput disable 14 &

feh --bg-scale ~/Pictures/Wallpaper/wallace.png &
# Launch polybar
#$HOME/.config/polybar_n/launch.sh &
$HOME/.config/polybar/launch.sh &

#bspc monitor eDP1 -s DP1
bspc monitor DP1 -s eDP1
bspc monitor \^1 -d 1 2 3 4 9 6 7
bspc monitor \^2 -d 5 8
#bspc monitor -d 1 2 3 4 9 6 7 8

bspc config border_width         1
bspc config window_gap          15

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config active_border_color "#2f343f"
bspc config focused_border_color "#65bfa8"
bspc config presel_feedback_color "#2f343f"
bspc config normal_border_color "#2f343f"
bspc config urgent_border_color "#f54e4e" 

bspc rule -a discord desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^3' follow=on
bspc rule -a vlc desktop='^4' follow=on
bspc rule -a obsidian desktop='^7' follow=on
bspc rule -a Spotify desktop=^5 follow=on
